export const ADD_COMMENT = 'ADD_COMMENT'

export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const COMMENT_LOADING = 'COMMENT_LOADING';

export const LOAD_DIEHES = 'LOAD_DISHES';
export const DISHES_LOADING = 'DISHES_LOADING'